apiVersion: v1
kind: Service
metadata:
  labels:
    service-label-key: service-label-value 
  name: service-name-loadbalancer
spec:
  type: LoadBalancer
  ports:
  - name: service-port-name
    port: 80
    protocol: TCP
  selector:
    deployment-label-key: deployment-label-value#for creating a deployment in kubernetes
 kubectl apply -f deployment.yaml
 #for internal communicating to angualar application
 kubeclt apply -f service.yaml
 #for access the angular application outside kubernetes
 kubeclt apply -f load-balancer-service.yaml